### ISSUE TITLE
Add Save Buffers To File Functionality

### ISSUE THREAD

**Issue by justinmoore** [nccgroup/Decoder-Improved#3]
Portswigger reached out to me saying that a user requested the ability to export decoder buffers to file. I'll work on implementing this within decoder improved.

**Comment by zehuanli** [comment]
Working state is now saved to extension setting in JSON data. The following items are saved:

- Tab names and current selection
- The bytes array of the first segment in each tab
- Text/hex, mode and configs (for mode) selection in each segment *(configs for HashMode not implemented yet)*

The user will basically see the same thing after a reload of the extension or restart of Burp. Byte arrays not in the first segment of a tab is not saved to reduce space consumption.

Something sounds buggy (due to Burp not supporting extension settings per project) is that the working state will be shared across all Burp instances (including temporary instance). A workaround may be creating a unique name of the setting profile per instance, but it's currently not ideal since there's no way we can delete the settings (unless Burp recycles them). See [here](https://support.portswigger.net/customer/portal/questions/12980903-saving-state-for-extension-data) for more info.

Another thing might be worth implementing is to add a button that allows the user to clear the setting manually, like at the end of a project to clean up all data.

**Comment by zehuanncc** [comment]
Working state is now saved to extension setting in JSON data. The following items are saved:

- Tab names and current selection
- The bytes array of the first segment in each tab
- Text/hex, mode and configs (for mode) selection in each segment *(configs for HashMode not implemented yet)*

The user will basically see the same thing after a reload of the extension or restart of Burp. Byte arrays not in the first segment of a tab is not saved to reduce space consumption.

Something sounds buggy (due to Burp not supporting extension settings per project) is that the working state will be shared across all Burp instances (including temporary instance). A workaround may be creating a unique name of the setting profile per instance, but it's currently not ideal since there's no way we can delete the settings (unless Burp recycles them). See [here](https://support.portswigger.net/customer/portal/questions/12980903-saving-state-for-extension-data) for more info.

Another thing might be worth implementing is to add a button that allows the user to clear the setting manually, like at the end of a project to clean up all data.
