### ISSUE TITLE
Black characters on dark background if using Dark theme

### ISSUE THREAD

**Issue by ipentest** [nccgroup/Decoder-Improved#37]
Hi Justin & Team,

Thanks for the wonderful tool. I found that if I am using a dark theme in Burp, the characters pasted into DI will be black on black background hence not very easy to read. Can you change this please?

Thanks
![di](https://user-images.githubusercontent.com/10952397/114567906-ad588900-9c41-11eb-8a34-4656ecdf226e.png)

**Comment by zehuanncc** [comment]
Thanks for finding the issue! It has been fixed in 754d97d9f451abe82b3b548351721cf01b6ce1d2. The extension in the Burp BApp Store may not be updated very soon, but you can download the updated jar file [here](https://github.com/nccgroup/Decoder-Improved/releases/latest) and load it manually in Burp Extender.
