### ISSUE TITLE
Trigger encoding explicitly

### ISSUE THREAD

**Issue by FranklinYu** [nccgroup/Decoder-Improved#6]
Currently decoding is triggered by selecting “Decode as…”, but encoding cannot be triggered directly. I work around it by first selecting “Encode as…” to triggers a new row, then back to “Decode as…”. I can think of two solutions:

1. Add a button “Go!” to trigger it explicitly.
2. Add a null element “Action:” so that the drop-down also changes for encoding.

**Comment by zehuanncc** [comment]
Hi @FranklinYu ,

In current version, if you click on any action (eg. "Plain", "URL") from the drop-down list, or click on any mode (eg. "Encode as", "Decode as"),  a new row will show up (if there isn't a row below) and the data will be processed based on the action you selected. The only action that will not be automatically triggered is the default combination "Encode as" + "Plain", which doesn't seem needed since the output will be the same.

Thanks for the issue and feel free to reopen it if you think the problem still exists.
